---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: parallels
platforms:
  - name: instance
    # yamllint disable-line rule:quoted-strings
    box: "${NAMESPACE:-bento}/${BOX:-debian-12}"
    memory: 2048
    cpus: 1
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
  playbooks:
    # yamllint disable-line rule:quoted-strings
    converge: "${MOLECULE_SCENARIO_DIRECTORY}/../../main.yml"
